<?php

namespace AppBundle\Repository;

/**
 * FavRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedditPostRepository extends \Doctrine\ORM\EntityRepository
{
}
